### ISSUE TITLE
Heater state not updating

### ISSUE THREAD

**Issue by antamy** [tagyoureit/nodejs-poolController#38] opened 2017-03-02 19:03 UTC
I have a choice of solar heat or gas heat.  In System Information, Heater State shows --- even when the heat is on.  Happy to debug if you can let me know what to do!

Thanks!

**Comment by tagyoureit** [comment] 2017-03-03 05:15
We either just took out this item from the UI, or are going to.  We aren't sure how it works (#13).  If you want to try to figure it out you can get our your best Enigma machine, look at the wiki to see what we know, and try to watch for packets that change when the heater turns on/off.  I've tried a handful of times to look at this and it's been inconclusive every time.  I'll close this as it's a dupe of the one mentioned above.  Cheers.

**Closed by tagyoureit** 2017-03-03 05:15 UTC
